// Generated by CoffeeScript 1.8.0
(function() {
  var faker, someWords, templates, trim;

  templates = require('../templates');

  faker = require('faker');

  someWords = function() {
    return faker.lorem.words().join(' ');
  };

  trim = function(string) {
    return string.replace(/\n\s*/g, '');
  };

  describe('templating of', function() {
    describe('text runs', function() {
      it('creates tags', function() {
        var TEXT, expected, result;
        TEXT = someWords();
        expected = "<w:r><w:t>" + TEXT + "</w:t></w:r>";
        result = trim(templates.text(TEXT));
        return result.should.eql(expected);
      });
      it('preserves whitespace', function() {
        var TEXT;
        TEXT = someWords();
        (templates.text(TEXT + ' ').indexOf('preserve') > -1).should.be["true"];
        (templates.text(' ' + TEXT).indexOf('preserve') > -1).should.be["true"];
        (templates.text(' ' + TEXT + ' ').indexOf('preserve') > -1).should.be["true"];
        return (templates.text(TEXT).indexOf('preserve') > -1).should.be["false"];
      });
      return it('escapes special characters', function() {
        return trim(templates.text('You & Me')).should.eql("<w:r><w:t>You &amp; Me</w:t></w:r>");
      });
    });
    describe('paragraphs', function() {});
    return describe('documents', function() {
      return it('includes the title', function() {
        var PARS, TITLE;
        TITLE = someWords();
        PARS = [];
        return (templates.document(TITLE, PARS).indexOf(TITLE) > -1).should.be["true"];
      });
    });
  });

}).call(this);
