// Generated by CoffeeScript 1.8.0
(function() {
  var DOCUMENT_XMLNS, HEADING_STYLES, OTHER_STYLES, XML_SPECIAL_CHARS, bookmark, e, entitySignatureBlock, individualSignatureBlock, isArray, isFunction, lineBreak, pageBreak, paragraph, paragraphStyle, preserve, reference, sectionParagraph, surroundedBySpace, tab, text, vanish, xmlescape;

  e = module.exports;

  isArray = Array.isArray || function(o) {
    return toString.call(o) === '[object Array]';
  };

  isFunction = function(o) {
    return typeof o === 'function' || false;
  };

  HEADING_STYLES = [null, 'Heading1', 'Heading2', 'Heading3', 'Heading4', 'Heading5', 'Heading6'];

  OTHER_STYLES = ['Title', 'Recital', 'Lead-In', 'SignatureBlock', 'Cross-Reference'];

  XML_SPECIAL_CHARS = {
    '&quot;': /"/g,
    '&apos;': /'/g,
    '&lt;': /</g,
    '&gt;': />/g,
    '&amp;': /&/g
  };

  xmlescape = e.xmlescape = function(string) {
    var escaped, re;
    for (escaped in XML_SPECIAL_CHARS) {
      re = XML_SPECIAL_CHARS[escaped];
      string = string.replace(re, escaped);
    }
    return string;
  };

  surroundedBySpace = function(string) {
    var first, last;
    first = string[0];
    last = string[string.length - 1];
    return first === ' ' || last === ' ';
  };

  preserve = 'xml:space="preserve"';

  text = e.text = function(input) {
    var space, style, t;
    if (isArray(input)) {
      ((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = input.length; _i < _len; _i++) {
          t = input[_i];
          _results.push(text(t));
        }
        return _results;
      })()).join('');
    } else if (typeof input === 'string') {
      t = input;
    } else {
      t = input.text;
      style = intput.style;
    }
    t = xmlescape(t);
    space = surroundedBySpace(t);
    if (style) {
      return "<w:r>\n  <w:rPr>\n    <w:rStyle w:val=\"" + style + "\"/>\n  </w:rPr>\n  <w:t" + (space ? ' ' + preserve : '') + ">" + t + "</w:t>\n</w:r>";
    } else {
      return "<w:r>\n  <w:t" + (space ? ' ' + preserve : '') + ">" + t + "</w:t>\n</w:r>";
    }
  };

  paragraphStyle = function(style) {
    return "<w:pPr>\n  <w:pStyle w:val=\"" + style + "\"/>\n</w:pPr>";
  };

  paragraph = function(content, style) {
    return "<w:p>\n  " + (style ? paragraphStyle(style) : void 0) + "\n  " + (text(content)) + "\n</w:p>";
  };

  vanish = "<w:rPr>\n  <w:vanish/>\n  <w:specVanish/>\n</w:rPr>";

  bookmark = function(name, inside) {
    name = xmlescape(name);
    return "<w:bookmarkStart w:id=\"" + name + "\" w:name=\"" + name + "\"/>\n" + (isFunction(inside) ? inside() : inside) + "\n<w:bookmarkEnd w:id=\"" + name + "\"/>";
  };

  reference = function(name) {
    name = xmlescape(name);
    return "<w:r>\n  <w:rPr>\n    <w:rStyle w:val=\"Cross-Reference\"/>\n  </w:rPr>\n  <w:fldChar w:fldCharType=\"begin\"/>\n</w:r>\n<w:r>\n  <w:rPr>\n    <w:rStyle w:val=\"Cross-Reference\"/>\n  </w:rPr>\n  <w:instrText xml:space=\"preserve\"> REF " + name + " \\w \\h \\* MERGEFORMAT </w:instrText>\n</w:r>\n<w:r>\n  <w:rPr>\n    <w:rStyle w:val=\"Cross-Reference\"/>\n  </w:rPr>\n</w:r>\n<w:r>\n  <w:rPr>\n    <w:rStyle w:val=\"Cross-Reference\"/>\n  </w:rPr>\n  <w:fldChar w:fldCharType=\"separate\"/>\n</w:r>\n<w:r>\n  <w:rPr>\n    <w:rStyle w:val=\"Cross-Reference\"/>\n  </w:rPr>\n  <w:t>Section ?</w:t>\n</w:r>\n<w:r>\n  <w:rPr>\n    <w:rStyle w:val=\"Cross-Reference\"/>\n  </w:rPr>\n  <w:fldChar w:fldCharType=\"end\"/>\n</w:r>";
  };

  sectionParagraph = function(headingContent, bodyContent, style) {
    return "<w:p>\n  " + (style ? paragraphStyle(style) : void 0) + "\n  " + vanish + "\n  " + (bookmark(headingContent, function() {
      return text(headingContent);
    })) + "\n</w:p>\n<w:p>\n  " + ((text(bodyContent)).join('')) + "\n</w:p>";
  };

  DOCUMENT_XMLNS = "xmlns:wpc=\"http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas\"\nxmlns:mc=\"http://schemas.openxmlformats.org/markup-compatibility/2006\"\nxmlns:o=\"urn:schemas-microsoft-com:office:office\"\nxmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"\nxmlns:m=\"http://schemas.openxmlformats.org/officeDocument/2006/math\"\nxmlns:v=\"urn:schemas-microsoft-com:vml\"\nxmlns:wp14=\"http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing\"\nxmlns:wp=\"http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing\"\nxmlns:w10=\"urn:schemas-microsoft-com:office:word\"\nxmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\"\nxmlns:w14=\"http://schemas.microsoft.com/office/word/2010/wordml\"\nxmlns:w15=\"http://schemas.microsoft.com/office/word/2012/wordml\"\nxmlns:wpg=\"http://schemas.microsoft.com/office/word/2010/wordprocessingGroup\"\nxmlns:wpi=\"http://schemas.microsoft.com/office/word/2010/wordprocessingInk\"\nxmlns:wne=\"http://schemas.microsoft.com/office/word/2006/wordml\"\nxmlns:wps=\"http://schemas.microsoft.com/office/word/2010/wordprocessingShape\"";

  e.document = function(title, paragraphs) {
    return "<w:document " + DOCUMENT_XMLNS + ">\n  <w:body>\n    " + (paragraph([title], 'Title')) + "\n  </w:body>\n</w:document>";
  };

  tab = "<w:r><w:tab/></w:r>";

  lineBreak = "<w:r><w:br/></w:r>";

  entitySignatureBlock = function(entity, name, title) {
    return "<w:p>\n  " + (paragraphStyle('SignatureBlockEntity')) + "\n</w:p>\n<w:p>\n  " + (paragraphStyle('SignatureBlock')) + "\n  " + (text('By: ')) + "\n  " + tab + "\n  " + lineBreak + "\n  " + (text('Name: ')) + "\n  " + (name ? text(name) : tab) + "\n  " + lineBreak + "\n  " + (text('Title: ')) + "\n  " + (title ? text(title) : tab) + "\n</w:p>";
  };

  individualSignatureBlock = function(name) {
    return "<w:p>\n  " + (paragraphStyle('SignatureBlock')) + "\n  " + tab + "\n  " + lineBreak + "\n  " + (text(name)) + "\n</w:p>";
  };

  pageBreak = "<w:p>\n  <w:pPr>\n    <w:spacing w:before=\"0\" w:after=\"150\" w:line=\"259\" w:lineRule=\"auto\"/>\n    <w:ind w:firstLine=\"0\"/>\n    <w:jc w:val=\"left\"/>\n  </w:pPr>\n  <w:r>\n    <w:br w:type=\"page\"/>\n  </w:r>\n</w:p>";

}).call(this);
